name: "Deploy okonni website on AWS"
description: "Builds static html files from Handlebars templates using npm, syncs dist folder to an AWS S3 bucket, invalidates an AWS CloudFront distribution, deploys Lambda functions using Serverless."
author: okonni
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: green